ABSphreak/readme-jokes

src/jokes.json
Sorry, the prettier extension spaced out the code, so all of jokes.json shows up as new. I have add jokes from 142-152.
=> Added 10 jokes to jokes.json

src/jokes.json
=> Joke 153 added

src/jokes.json
=> added joke to jokes.json

src/jokes.json
=> Two jokes added

api/index.js, src/jokes.json, src/utils.js
1. Fixed, jokes not randomly generated after each GET request to /api.
2. Added cache age options.
3. Removed a reused joke in jokes.json
4. Also fixed the index variable it's value can be greater than the jokes array.
=> Randomization fix

src/jokes.json
Added a few jokes, please check them.
=> added new jokes

src/jokes.json
Added new jokes please check them.
=> Adding few dev jokes

api/index.js
Added option to customize themes, users can now add additional URL query parameter along with theme to customize specific things in the rendered output.
=> Added option to customize themes

README.md, api/index.js, src/jokes.json, src/themes.json, src/utils.js
- Added multiple new themes (from github-readme-stats). 
- Added a `random` theme option.
- Added a new joke.
- Updated Readme for all new changes.
Most of the new theme were taken directly from github-readme-stats, so for some the question color and answer color scheme might not look correct. Please add a issue or a note in readme encouraging people to fix this. Also most of the new themes have an empty `codeColor` because getting a code tag in the joke is not consistent and going through each theme and finding a matching color would take a lot of time. Please add a note for this too. The `random` theme option allows users to get a random theme each time a request is made. And finally a joke that I had in my head for a while.
=> Added lots of new things

src/jokes.json
=> added 2 jokes

src/jokes.json
=> Add a question-answer joke

src/jokes.json
=> Fix Minor Typo

src/jokes.json
=> Added spiders joke

src/jokes.json
=> Added joke on line 751

src/jokes.json
I saw 2 spelling mistakes, so I fixed them!
=> Fixed 2 typos

src/jokes.json
You can add the joke if you like, I find it pretty hilarious.
=> add joke. 183

README.md
So basically, before we had to paste every URL of the available themes to see which ones we like the best; however, it took a lot of time. So, I have made a little table (it's huge) where users can see how each theme looks like when implemented in the jokes card. If this pull request is accepted, I will continue to work on more features whihc I have planned about this project, so it can reach out to more people! Glad to help!
PREVIEW
=> I have created a table so anyone who wants to use the cards can get a preview

src/jokes.json
Please add "hacktoberfest-accepted" label
=> Added foo bar joke 186

.eslintrc.json, api/index.js, package.json, src/jokes.json, src/renderJokesCard.js, src/utils.js
It's pretty minor but I did what I think could have been done :smile:
=> Removed same joke and setup linting 

src/jokes.json
=> new joke added

README.md
added examples. restructured and refactored the customization section.
did a thorough explanation with examples of the customization as i myself needed this and felt there was steps missing.
=> Updated the guide on customization

src/renderJokesCard.js
Font size and card width is adjusted according to the available width of the screen. 
**Note:-** _If you are testing it with the developer tools, don't forget to reload the page whenever viewport is changed!_
Let me know if any issue still arises.
Have a Nice Day! 😄
=> Made Responsive
